# Generated by Django 4.1 on 2023-01-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subsriber', 'verbose_name_plural': 'A lot of subscribers'},
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='numbers',
            field=models.CharField(blank=True, default=None, max_length=13, null=True),
        ),
    ]
