# Generated by Django 4.1 on 2023-01-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_productinorder_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_activate',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
