# Generated by Django 4.1 on 2023-01-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_is_activate_order_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
